### ISSUE TITLE
Hiding vanished players

### ISSUE THREAD

**Issue by Loapu** [voruti/VelocityPlayerListQuery#26]
Hey, would it be possible to hide vanished players from the list? You could hook in [PAPIProxyBridge](https://modrinth.com/plugin/papiproxybridge) for example and use the PAPI placeholders to detect players in a vanished state.

Kind regards,
Loapu

**Comment by voruti** [comment]
Sounds useful. Which mods/plugins can use the bridge (on the mc server side) i.e. which mod/plugin are you currently using to vanish players?

Since I'm currently not using anything like that, I probably don't find the time to implement this myself in the near future. You're welcome to open a pull request if you like to do the implementation...
